name: flutter_skin_color
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8 # Untuk ikon iOS
  camera: ^0.11.0+2 # Untuk fitur scan kamera
  http: ^1.2.2 # Untuk API service
  flutter_lints: ^5.0.0 # Untuk rekomendasi linting terbaik
  image_picker: ^0.8.5+3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # Uncomment dan tambahkan asset jika diperlukan
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
